### ISSUE TITLE
Download dataset from url

### ISSUE THREAD

**Issue by vinzeebreak** [vinzeebreak/dafter#81]
Feature request by @chrplr in #80

**Comment by chrplr** [comment]
Maybe a new command, rather than an option as I suggested (?)
I.e, something like:

dafter import-config xxxxx.json  (xxxx.json is an url or local file)
dafter get xxxx

**Comment by vinzeebreak** [comment]
I think ` dafter get xxxx` where "xxxx" can be:

- the name of a dataset (what's implemented right now)
- a url
- the path to a json file

So that the user does not have to "think" about the parameters, the flags or the command to run since it's the same command for the 3.

**Comment by chrplr** [comment]
Yes! You are right : keep it simple.
